language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm install; npm run build
deploy:
  provider: heroku
  app: webapps05
  api-key: 03b286f8-6ecb-460f-8e9d-1245a883a64c
on:
  branch: master
